import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { BiLinkExternal } from 'react-icons/bi'

export default function Home() {
  return (
    <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <meta name='viewport' content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <section className="bg-slate-200 w-full h-screen text-gray-600 body-font">
      <div className="container mx-auto flex px-5 py-24 items-center justify-center flex-col">
        <Image alt="hero" width={300} height={200} src="/vercel.svg" />
        <div className="text-center lg:w-2/3 w-full">
          <h1 className="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900">Welcome to the <span className='text-blue-600'>Next + Tailwind!</span></h1>
          <p className="mb-8 text-2xl leading-relaxed">
            This is a starter template for Next.js + Tailwind CSS.</p>
          <div className="flex justify-center">
            <button className="flex items-center font-semibold text-white bg-gray-700 border-0 py-2 px-6 focus:outline-none hover:bg-black rounded text-lg">
            <span className='mr-2'>
              <Link href="https://nextjs.org/docs/getting-started">Next.js</Link>
              </span>
              <BiLinkExternal/>
              </button>
            <button className="ml-4 flex items-center font-semibold text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg">
            <span className='mr-2'>
              <Link href="https://tailwindcss.com/docs/installation">Tailwind CSS</Link>
              </span>
              <BiLinkExternal/>
            </button>
          </div>
        </div>
      </div>
    </section>
    </>
  )
}
